Update documentation to mention all language-server settings
StevenLooman/sonar-magik pull request #73
Opened 2024-07-11 10:50 UTC by sebastiaanspeck

2024-07-14 21:00 UTC, StevenLooman requested changes
Thanks. Just a small request for a change.

2024-07-14 21:00 UTC, StevenLooman commented on magik-language-server/client-vscode/package.json
> +					"description": "Path to gis_aliases file -- ignored by language server.",
Perhaps instead of `ignored by language server`, specify where it is (only) used. I.e., something like `only used by vscode extension`.

2024-07-14 21:00 UTC, StevenLooman commented on magik-language-server/client-vscode/package.json
> +					"description": "Path to environment file --ignored by language server.",
Perhaps instead of `ignored by language server`, specify where it is (only) used. I.e., something like `only used by vscode extension`.

2024-07-14 21:07 UTC, sebastiaanspeck commented on magik-language-server/client-vscode/package.json
> +					"description": "Path to environment file --ignored by language server.",
Fixed! Also fixed the others that used `-- ignored by language server`.

2024-07-14 21:07 UTC, sebastiaanspeck commented on magik-language-server/client-vscode/package.json
> +					"description": "Path to gis_aliases file -- ignored by language server.",
Fixed! Also fixed the others that used `-- ignored by language server`.

2024-07-14 21:11 UTC, sebastiaanspeck commented
I saw a thing that made me question the use of `magik.smallworldGis`. Looking at the code, it is only used in the VS Code extension, but the documentation suggests the language server uses it too; [`getSmallworldGis()`](https://github.com/search?q=repo%3AStevenLooman%2Fmagik-tools+getSmallworldGis&type=code) seems unused as well, which might created the confusion in the documentation

2024-07-20 21:03 UTC, merged

2024-07-20 21:03 UTC, StevenLooman commented
Thanks!

2024-07-21 05:55 UTC, sebastiaanspeck commented
> Thanks! Removed the unused method as well.

That would mean we need to move that documentation part to the VS Code-specific part

2024-07-21 18:52 UTC, StevenLooman commented
Yes. In fact, it is Fixedalready in the VSCode specific part: